<a href="https://colab.research.google.com/github/JissmonJoshy/DataScience/blob/main/Jissmon_Decision_trees.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Aim:** Program to implement decision trees using any standard dataset available in the public domain and find the accuracy of the algorithm.

**Short notes**

Decision tree is a type of supervised learning algorithm (having a predefined target variable) that is mostly used in classification problems. It works for both categorical and continuous input and output variables. In this technique, we split the population or sample into two or more homogeneous sets (or sub-populations) based on most significant splitter / differentiator in input variables.

**Used Python Packages**:

**sklearn** :
In python, sklearn is a machine learning package which include a lot of ML algorithms. Here, we are using some of its modules like train_test_split, DecisionTreeClassifier and accuracy_score.

**NumPy** :
It is a numeric python module which provides fast maths functions for calculations.
It is used to read data in numpy arrays and for manipulation purpose.

**Pandas** :
Used to read and write different files.
Data manipulation can be done easily with dataframes.



**Important Terminology related to Tree based Algorithms**

**Root Node**: It represents entire population or sample and this further gets divided into two or more homogeneous sets.

**Splitting**: It is a process of dividing a node into two or more sub-nodes.

**Decision Node**: When a sub-node splits into further sub-nodes, then it is called decision node.

**Leaf/ Terminal Node**: Nodes do not split is called Leaf or Terminal node.

**Pruning**: When we remove sub-nodes of a decision node, this process is called pruning. You can say opposite process of splitting.

**Branch / Sub-Tree**: A sub section of entire tree is called branch or sub-tree.

**Parent and Child Node**: A node, which is divided into sub-nodes is called parent node of sub-nodes where as sub-nodes are the child of parent node.

In [ ]:
#import the modules
import numpy as np
import pandas as pd
from sklearn.model_selection import  train_test_split
#load iris data
df=pd.read_csv("https://raw.githubusercontent.com/JissmonJoshy/DataScience/main/iris-species%20(2).csv")


In [ ]:
#Display the number of rows & columns in dataframe
print("number of rows & columns",df.shape)
df.columns

number of rows & columns (150, 6)


Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
#Perform Train Test Split
x=df[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y=df['Species']
#print(x)
#print(y)
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=14,stratify=y)

In [ ]:
#Construct decission tree classifier with criterion='entropy' with min_samples_split to 50. Default value is 2
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
data=DecisionTreeClassifier(criterion='entropy')
data.fit(x_train,y_train)
pred=data.predict(x_test)

#Display Accuracy on test data
acc=accuracy_score(y_test,pred)
print("Accuracy =>",acc)

Accuracy => 0.9555555555555556


In [ ]:
#visualise the decision tree


from sklearn.tree import export_graphviz
from six import StringIO
from IPython.display import Image
import pydotplus



In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,pred))

[[15  0  0]
 [ 0 15  0]
 [ 0  2 13]]
