<a href="https://colab.research.google.com/github/JissmonJoshy/DataScience/blob/main/Jiss_Mon_Joshy_of_CO1_NumpyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# program to create an array of all the even integers from 20 to 80

import numpy as np
a=np.arange(20,81,2)
print(a)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


In [ ]:
#Write a program to create a numpy array and perform element-wise comparison (greater, greater_equal, less than, lesser_equal).

a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 2, 2, 4, 6])
print(a)
print(b)
print("Greater Than:",np.greater(a,b))
print("Equal:",np.greater_equal(a,b))
print("Less Than:",np.less_equal(a,b))

[1 2 3 4 5]
[3 2 2 4 6]
Greater Than: [False False  True False False]
Equal: [False  True  True  True False]
Less Than: [ True  True False  True  True]


In [ ]:
#program to multiply two given arrays of same size

a1 = np.array([4,9,2])
a2 = np.array([3 ,8 , 2])
print(a1)
print(a2)
x=np.multiply(a1,a2)
print(x)

[4 9 2]
[3 8 2]
[12 72  4]


In [ ]:
#Program to save a given array to a text file and load it

import os

a1 = np.arange(start=0,stop=16).reshape(4,4)
print(a1)

h = 'c1 c2 c3 c4'
np.savetxt("file.txt",a1,fmt="%d",header=h)
print("\nfile.txt of loadtxt()\n")
print(np.loadtxt("file.txt"))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

file.txt of loadtxt()

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
